


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer DEFAULT 50) RETURNS TABLE("nickname" "text", "weighted_percent" double precision, "questions_answered" bigint, "attempts" bigint, "last_played" timestamp with time zone)
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select
    p.nickname,
    (sum(qa.correct)::float / nullif(sum(qa.total), 0)) as weighted_percent,
    sum(qa.total) as questions_answered,
    count(*) as attempts,
    max(qa.created_at) as last_played
  from public.quiz_attempts qa
  join public.profiles p on p.id = qa.user_id
  where qa.category = p_category
    and qa.difficulty = p_difficulty
  group by p.nickname
  having sum(qa.total) >= 50
  order by weighted_percent desc, questions_answered desc, last_played asc
  limit least(greatest(p_limit, 1), 200);
$$;


ALTER FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."quiz_attempts" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "category" integer NOT NULL,
    "difficulty" "text" NOT NULL,
    "correct" integer NOT NULL,
    "total" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "quiz_attempts_correct_check" CHECK (("correct" >= 0)),
    CONSTRAINT "quiz_attempts_difficulty_check" CHECK (("difficulty" = ANY (ARRAY['easy'::"text", 'medium'::"text", 'hard'::"text"]))),
    CONSTRAINT "quiz_attempts_total_check" CHECK (("total" > 0))
);


ALTER TABLE "public"."quiz_attempts" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."leaderboard_weighted" AS
 SELECT "category",
    "difficulty",
    "user_id",
    (("sum"("correct"))::double precision / (NULLIF("sum"("total"), 0))::double precision) AS "weighted_percent",
    "sum"("total") AS "questions_answered",
    "count"(*) AS "attempts",
    "max"("created_at") AS "last_played"
   FROM "public"."quiz_attempts" "qa"
  GROUP BY "category", "difficulty", "user_id"
 HAVING ("sum"("total") >= 50);


ALTER VIEW "public"."leaderboard_weighted" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "nickname" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."leaderboard_weighted_named" AS
 SELECT "lw"."category",
    "lw"."difficulty",
    "p"."nickname",
    "lw"."weighted_percent",
    "lw"."questions_answered",
    "lw"."attempts",
    "lw"."last_played"
   FROM ("public"."leaderboard_weighted" "lw"
     JOIN "public"."profiles" "p" ON (("p"."id" = "lw"."user_id")));


ALTER VIEW "public"."leaderboard_weighted_named" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."my_weighted_stats" AS
 SELECT "user_id",
    "category",
    "difficulty",
    (("sum"("correct"))::double precision / (NULLIF("sum"("total"), 0))::double precision) AS "weighted_percent",
    "sum"("total") AS "questions_answered",
    "count"(*) AS "attempts",
    "max"("created_at") AS "last_played"
   FROM "public"."quiz_attempts"
  GROUP BY "user_id", "category", "difficulty";


ALTER VIEW "public"."my_weighted_stats" OWNER TO "postgres";


ALTER TABLE "public"."quiz_attempts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quiz_attempts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."scores" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "score" integer NOT NULL,
    "total" integer NOT NULL,
    "category" integer,
    "difficulty" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."scores" OWNER TO "postgres";


ALTER TABLE "public"."scores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."scores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_nickname_key" UNIQUE ("nickname");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quiz_attempts"
    ADD CONSTRAINT "quiz_attempts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."scores"
    ADD CONSTRAINT "scores_pkey" PRIMARY KEY ("id");



CREATE INDEX "quiz_attempts_bucket_idx" ON "public"."quiz_attempts" USING "btree" ("category", "difficulty", "created_at" DESC);



CREATE INDEX "quiz_attempts_user_idx" ON "public"."quiz_attempts" USING "btree" ("user_id", "created_at" DESC);



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quiz_attempts"
    ADD CONSTRAINT "quiz_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."scores"
    ADD CONSTRAINT "scores_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "insert own attempts" ON "public"."quiz_attempts" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "insert own profile" ON "public"."profiles" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "insert own scores" ON "public"."scores" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."quiz_attempts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read own attempts" ON "public"."quiz_attempts" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "read own scores" ON "public"."scores" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "read profiles" ON "public"."profiles" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."scores" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update own profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) TO "service_role";


















GRANT ALL ON TABLE "public"."quiz_attempts" TO "anon";
GRANT ALL ON TABLE "public"."quiz_attempts" TO "authenticated";
GRANT ALL ON TABLE "public"."quiz_attempts" TO "service_role";



GRANT ALL ON TABLE "public"."leaderboard_weighted" TO "anon";
GRANT ALL ON TABLE "public"."leaderboard_weighted" TO "authenticated";
GRANT ALL ON TABLE "public"."leaderboard_weighted" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."leaderboard_weighted_named" TO "anon";
GRANT ALL ON TABLE "public"."leaderboard_weighted_named" TO "authenticated";
GRANT ALL ON TABLE "public"."leaderboard_weighted_named" TO "service_role";



GRANT ALL ON TABLE "public"."my_weighted_stats" TO "anon";
GRANT ALL ON TABLE "public"."my_weighted_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."my_weighted_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quiz_attempts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quiz_attempts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quiz_attempts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."scores" TO "anon";
GRANT ALL ON TABLE "public"."scores" TO "authenticated";
GRANT ALL ON TABLE "public"."scores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer DEFAULT 50) RETURNS TABLE("nickname" "text", "weighted_percent" double precision, "questions_answered" bigint, "attempts" bigint, "last_played" timestamp with time zone)
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select
    p.nickname,
    (sum(qa.correct)::float / nullif(sum(qa.total), 0)) as weighted_percent,
    sum(qa.total) as questions_answered,
    count(*) as attempts,
    max(qa.created_at) as last_played
  from public.quiz_attempts qa
  join public.profiles p on p.id = qa.user_id
  where qa.category = p_category
    and qa.difficulty = p_difficulty
  group by p.nickname
  having sum(qa.total) >= 30
  order by weighted_percent desc, questions_answered desc, last_played asc
  limit least(greatest(p_limit, 1), 200);
$$;


ALTER FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."quiz_attempts" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "category" integer NOT NULL,
    "difficulty" "text" NOT NULL,
    "correct" integer NOT NULL,
    "total" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "quiz_attempts_correct_check" CHECK (("correct" >= 0)),
    CONSTRAINT "quiz_attempts_difficulty_check" CHECK (("difficulty" = ANY (ARRAY['easy'::"text", 'medium'::"text", 'hard'::"text"]))),
    CONSTRAINT "quiz_attempts_total_check" CHECK (("total" > 0))
);


ALTER TABLE "public"."quiz_attempts" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."leaderboard_weighted" AS
 SELECT "category",
    "difficulty",
    "user_id",
    (("sum"("correct"))::double precision / (NULLIF("sum"("total"), 0))::double precision) AS "weighted_percent",
    "sum"("total") AS "questions_answered",
    "count"(*) AS "attempts",
    "max"("created_at") AS "last_played"
   FROM "public"."quiz_attempts" "qa"
  GROUP BY "category", "difficulty", "user_id"
 HAVING ("sum"("total") >= 30);


ALTER VIEW "public"."leaderboard_weighted" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "nickname" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."leaderboard_weighted_named" AS
 SELECT "lw"."category",
    "lw"."difficulty",
    "p"."nickname",
    "lw"."weighted_percent",
    "lw"."questions_answered",
    "lw"."attempts",
    "lw"."last_played"
   FROM ("public"."leaderboard_weighted" "lw"
     JOIN "public"."profiles" "p" ON (("p"."id" = "lw"."user_id")));


ALTER VIEW "public"."leaderboard_weighted_named" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."my_weighted_stats" AS
 SELECT "user_id",
    "category",
    "difficulty",
    (("sum"("correct"))::double precision / (NULLIF("sum"("total"), 0))::double precision) AS "weighted_percent",
    "sum"("total") AS "questions_answered",
    "count"(*) AS "attempts",
    "max"("created_at") AS "last_played"
   FROM "public"."quiz_attempts"
  GROUP BY "user_id", "category", "difficulty";


ALTER VIEW "public"."my_weighted_stats" OWNER TO "postgres";


ALTER TABLE "public"."quiz_attempts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quiz_attempts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."scores" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "score" integer NOT NULL,
    "total" integer NOT NULL,
    "category" integer,
    "difficulty" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."scores" OWNER TO "postgres";


ALTER TABLE "public"."scores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."scores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_nickname_key" UNIQUE ("nickname");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quiz_attempts"
    ADD CONSTRAINT "quiz_attempts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."scores"
    ADD CONSTRAINT "scores_pkey" PRIMARY KEY ("id");



CREATE INDEX "quiz_attempts_bucket_idx" ON "public"."quiz_attempts" USING "btree" ("category", "difficulty", "created_at" DESC);



CREATE INDEX "quiz_attempts_user_idx" ON "public"."quiz_attempts" USING "btree" ("user_id", "created_at" DESC);



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quiz_attempts"
    ADD CONSTRAINT "quiz_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."scores"
    ADD CONSTRAINT "scores_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "insert own attempts" ON "public"."quiz_attempts" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "insert own profile" ON "public"."profiles" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "insert own scores" ON "public"."scores" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."quiz_attempts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read own attempts" ON "public"."quiz_attempts" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "read own scores" ON "public"."scores" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "read profiles" ON "public"."profiles" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."scores" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update own profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_leaderboard_weighted"("p_category" integer, "p_difficulty" "text", "p_limit" integer) TO "service_role";


















GRANT ALL ON TABLE "public"."quiz_attempts" TO "anon";
GRANT ALL ON TABLE "public"."quiz_attempts" TO "authenticated";
GRANT ALL ON TABLE "public"."quiz_attempts" TO "service_role";



GRANT ALL ON TABLE "public"."leaderboard_weighted" TO "anon";
GRANT ALL ON TABLE "public"."leaderboard_weighted" TO "authenticated";
GRANT ALL ON TABLE "public"."leaderboard_weighted" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."leaderboard_weighted_named" TO "anon";
GRANT ALL ON TABLE "public"."leaderboard_weighted_named" TO "authenticated";
GRANT ALL ON TABLE "public"."leaderboard_weighted_named" TO "service_role";



GRANT ALL ON TABLE "public"."my_weighted_stats" TO "anon";
GRANT ALL ON TABLE "public"."my_weighted_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."my_weighted_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quiz_attempts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quiz_attempts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quiz_attempts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."scores" TO "anon";
GRANT ALL ON TABLE "public"."scores" TO "authenticated";
GRANT ALL ON TABLE "public"."scores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























